# most of this is ripped straight from Jest's config, since I'm sure they know their shit:
# https://github.com/facebook/jest/blob/master/.circleci/config.yml
aliases:
  - &node-maintenance-lts
    image: circleci/node:8 # to be updated to 10 once 2020 hits

version: 2
jobs:
  install-and-lint:
    docker:
      - &node-active-lts
        image: circleci/node:lts
    steps:
      - checkout
      - &restore-cache
        restore-cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save-cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint --format junit -o reports/junit/eslint/results.xml
      - &store-test-results
        store_test_results:
          path: reports/junit

  test-node-maintenance-lts:
    docker:
      - <<: *node-maintenance-lts
        environment: &base-env
          KNEX_CONNECTION_USER: &test-user knex
          KNEX_CONNECTION_DATABASE: &test-db test
      - &redis
        image: circleci/redis
      - &postgres
        image: circleci/postgres
        environment:
          POSTGRES_USER: *test-user
          POSTGRES_DB: *test-db
    steps:
      - checkout
      - *restore-cache
      - &build
        run: yarn build
      - run:
          environment:
            JEST_JUNIT_OUTPUT_NAME: reports/junit/jest/node-maintenance-lts.xml
          command: &test yarn test --ci --runInBand --reporters=default --reporters=jest-junit --forceExit
      - *store-test-results

  # only this one gets to report coverage
  test-node-active-lts:
    docker:
      - <<: *node-active-lts
        environment: *base-env
      - *redis
      - *postgres
    steps:
      - checkout
      - *restore-cache
      - *build
      - run:
          environment:
            JEST_JUNIT_OUTPUT_NAME: reports/junit/jest/node-active-lts.xml
          command: yarn test --coverage --ci --runInBand --reporters=default --reporters=jest-junit --forceExit
      - *store-test-results
      - run: yarn coverage

  deploy-docs:
    docker:
      - *node-active-lts
    steps:
      - checkout
      - *restore-cache
      - run: yarn docs:build
      - run: yarn docs:deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-and-lint
      - test-node-maintenance-lts:
          requires:
            - install-and-lint
      - test-node-active-lts:
          requires:
            - install-and-lint
      - deploy-docs:
          requires:
            - install-and-lint
          filters: &master-branch-only
            branches:
              only:
                - master
