# most of this is ripped straight from Jest's config, since I'm sure they know their shit:
# https://github.com/facebook/jest/blob/master/.circleci/config.yml
version: 2
jobs:
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - &restore-cache
        restore-cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - &install
        run: yarn install --frozen-lockfile
      - &save-cache
        save-cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - &store-test-results
        store_test_results:
          path: reports/junit

  test:
    docker:
      - image: circleci/node
        environment: &base-env
          KNEX_CONNECTION_USER: &test-user knex
          KNEX_CONNECTION_DATABASE: &test-db test
      - image: circleci/redis
      - image: circleci/postgres
        environment:
          POSTGRES_USER: *test-user
          POSTGRES_DB: *test-db
    steps:
      - checkout
      - *restore-cache
      - *install
      - *save-cache
      - run:
          environment:
            JEST_JUNIT_OUTPUT_NAME: reports/junit/jest/results.xml
          command: &test yarn test --coverage --ci --runInBand --reporters=default --reporters=jest-junit --forceExit
      - *store-test-results
      - run: yarn coverage

  docs-deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - *restore-cache
      - *install
      - *save-cache
      - run: yarn docs:build
      - run: yarn docs:deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - test
      - docs-deploy:
          requires:
            - lint
          filters: &master-branch-only
            branches:
              only:
                - master
