anonymous:
  grants:
    - resource: User
      action: read
      attributes: &defaultUserReadAccess
        - '*'
        - '!email'
    - resource: User
      action: create
      attributes: &defaultUserWriteAccess
        - '*'
        - '!role'
        - '!verified'

user:
  grants:
    - resource: User
      action: read
      attributes: *defaultUserReadAccess
    - resource: User
      action: read
      attributes:
        - email
      condition: &is-self
        Fn: EQUALS
        args:
          username: $.req.user.username
    - resource: User
      action: update
      attributes: *defaultUserWriteAccess
      condition: *is-self
    - resource: User
      action: delete
      condition:
        Fn: EQUALS
        args:
          true: $.req.body.confirm

admin:
  extends:
    role: user
  grants:
    - resource: User
      action: update
      attributes:
        - role
      condition:
        Fn: NOT_EQUALS
        args:
          role: admin
