anonymous:
  grants:
    - resource: user
      action: read
      attributes: ['*', '!email']
    - resource: user
      action: create
      attributes: ['*', '!role']

user:
  grants:
    - resource: user
      action: read
      attributes: ['*', '!email']
    - resource: user
      action: read
      attributes: ['email']
      condition:
        Fn: EQUALS
        args:
          requester: $.user.id
    - resource: user
      action: [update, delete]
      attributes: ['*', '!role']
      condition:
        Fn: EQUALS
        args:
          requester: $.user.id

admin:
  extends:
    role: user
  grants:
    - resource: user
      action: update
      attributes: ['role']
      # TODO: admins shouldn't be able to affect other admins' status?
      # TODO: but at the same time, they should be able to "step down" on their own
      condition:
        Fn: NOT_EQUALS
        args:
          role: admin
