port: 3000
timeout: 60e+3 # 1 minute, in milliseconds
requestIdHeader: X-Request-Id
proxy: false

logger:
  options:
    level: debug
    prettyPrint:
      translateTime: true
  # https://github.com/fastify/fastify/blob/master/lib/logger.js
  serializers:
    req:
      - id
      - method
      - url
      - user
      - body
    res:
      - statusCode
      - statusMessage

session:
  secret: nyaa
  cookie:
    sameSite: lax # CSRF protection
    maxAge: 86400e+3 # 1 day, in milliseconds
    rememberMe: 2.592e+9 # 30 days, in milliseconds
  resave: false
  rolling: true
  saveUninitialized: false # GDPR compliance

ratelimit:
  max: 0

redis:
  url: redis://localhost

# https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue
queue:
  defaultJobOptions:
    removeOnComplete: true

# extends queue
mailQueue:
  defaultJobOptions:
    removeOnFail: true # we don't need to store failed email "jobs"
  # this is just an SES example. modify as you see fit for your service (especially Sendgrid)
  limiter:
    max: 14
    duration: 1 # 1 sec in millis

database:
  # available clients: https://knexjs.org/#Installation-node
  # note that while you *can* use other clients, some of the base class's "magic methods"
  # that utilize .returning('*') will NOT be available on anything other than pg/mssql
  client: pg
  connection: postgres://localhost/app
  debug: true

mail:
  # for maildev, we don't need credentials
  smtp:
    service: maildev
  # https://nodemailer.com/message
  defaults:
    from: test@example.com
