port: 3000
timeout: 60e+3 # 1 minute, in milliseconds
requestIdHeader: X-Request-Id
proxy: false

logger:
  options:
    level: debug
    prettyPrint:
      translateTime: true
      ignore: pid,hostname,boot
  # https://github.com/fastify/fastify/blob/master/lib/logger.js
  serializers:
    req:
      - id
      - method
      - url
      - user
      - body
    res:
      - statusCode
      - statusMessage

session:
  secret: nyaa
  cookie:
    sameSite: lax # CSRF protection
    maxAge: 86400e+3 # 1 day, in milliseconds
    rememberMe: 2.592e+9 # 30 days, in milliseconds
  resave: false
  rolling: true
  saveUninitialized: false # GDPR compliance

ratelimit:
  max: 0

redis:
  url: redis://localhost

queue:
  defaultJobOptions:
    attempts: 3
    removeOnComplete: true
    backoff:
      type: exponential
      delay: 15e+3 # 15 seconds, in milliseconds

database:
  # available clients: https://knexjs.org/#Installation-node
  # note that while you *can* use other clients, some of the base class's "magic methods"
  # that utilize .returning('*') will NOT be available on anything other than pg
  client: pg
  connection: postgres://localhost/app
  debug: true

mail:
  # for maildev, we don't need credentials
  smtp:
    service: maildev
  defaults:
    from: test@example.com
