logger:
  options:
    prettyPrint:
      colorize: false
  serializers:
    req:
      - id
      - method
      - url
      - user
      # skip body because body.req exists for some stupid reason
  destination: logs/test-output.log

database:
  debug: false
