/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  id?: number
  username: string
  email: string
  password: string
  verified?: boolean
  role?: 'user' | 'admin'
}
